dcm_planner:
    step_time: 0.75 #second
    step_size: 0.3 #meter
    n_steps: 10
    dt: 0.01 #second
    contact_names: ["l_sole","r_sole"]
    contact_sequence: [2, 1]
    contact_dimensions: [0.2,0.1,0.01] #length(x), width(y), height(z)
